[phases.setup]
aptPkgs = ["ffmpeg", "python3", "python3-pip"]

[phases.install]
cmds = [
  "npm install --ignore-scripts",
  "pip3 install -U yt-dlp --break-system-packages"
]

[start]
cmd = "node server.js"
